export const GET_CAMPGROUNDS = "GET_CAMPGROUNDS";
export const ADD_CAMPGROUND = "ADD_CAMPGROUND";
export const DELETE_CAMPGROUND = "DELETE_CAMPGROUND";
export const CAMPGROUNDS_LOADING = "CAMPGROUNDS_LOADING";
